---
title: "Welcome to ALA Labs"
description: "This site is a resource for coding projects that use data sourced from the ALA. We hope that users will find interesting content, whether their focus is ecological modelling, data visualisation, or simply investigating the natural world through a digital lens. Enjoy!"
output: 
  distill::distill_article:
    includes:
      in_header: hero-image.html
site: distill::distill_website
---

```{r, include = FALSE}
# To change the hero-image:

# open theme.css
# find the .hero-image section
# under background-image, change the "url(images/galah_image.jfif);" to a another image url
```

```{r, include=FALSE}
library(htmltools)
source("R/functions.R")
```

```{r meta-details, include=FALSE, results = 'asis'}
# This edits meta details that display when people search for website on search engines
library(metathis)

meta() %>%
  meta_social(
    title = "ALA LABS",
    description = "Demo projects, experiments and debugging data from the Atlas of Living Australia",
    url = "https://labs.ala.org.au",
    image = "https://labs.ala.org.au/galah_image.png",
    image_alt = "Labs - Atlas of Living Australia",
    og_type = "website",
    og_author = "Atlas of Living Australia",
    twitter_card_type = "summary",
    twitter_creator = "@atlaslivingaust"
  )
```

 


<center> <h1>Data Visualisation</h1> </center>

<center> <span style = "font-style: italic">Click to see related posts on each topic</span> </center>

:::l-page

```{r, echo = FALSE}
tags$div(class = "category-row",
         
  tags$div( 
    class = "category-column",
    tags$a(href = "posts.html#category:Counts",
      tags$img(
        href = "posts.html#category:Counts",
        src = "images/vectors/barplot.svg",
        class = "category-image plum"
  )),
  tags$p(
    tags$h3(style = "text-align:center",
      tags$a(href = "posts.html#category:Counts", "Counts")))),
  
  tags$div( 
    class = "category-column",
    tags$a(href = "posts.html#category:Maps",
      tags$img(
        href = "posts.html#category:Maps",
        src = "images/vectors/Australia.svg",
        class = "category-image plum"
  )),
  tags$p(
    tags$h3(style = "text-align:center",
      tags$a(href = "posts.html#category:Maps", "Maps")))),
  
  tags$div( 
    class = "category-column",
    tags$a(href = "posts.html#category:Trees",
      tags$img(
        href = "posts.html#category:Trees",
        src = "images/vectors/tree.svg",
        class = "category-image plum"
  )),
  tags$p(
    tags$h3(style = "text-align:center",
      tags$a(href = "posts.html#category:Trees", "Trees"))))
  
  )
```


:::

<center> <h1>Taxonomy</h1> </center>

<center> <span style = "font-style: italic">Click to see related posts on each topic</span> </center>

:::l-page

```{r, echo = FALSE}
tags$div(class = "category-row",
         
  tags$div( 
    class = "category-column",
    tags$a(href = "posts.html#category:Plantae",
      tags$img(
        href = "posts.html#category:Plantae",
        src = "images/vectors/eucalypt.svg",
        class = "category-image sage"
  )),
  tags$p(
    tags$h3(style = "text-align:center",
      tags$a(href = "posts.html#category:Plantae", "Plants")))),
  
  tags$div( 
    class = "category-column",
    tags$a(href = "posts.html#category:Aves",
      tags$img(
        href = "posts.html#category:Aves",
        src = "images/vectors/falco.svg",
        class = "category-image sage",
        style = "height: 120px; width: auto;"
  )),
  tags$p(
    tags$h3(style = "text-align:center",
      tags$a(href = "posts.html#category:Aves", "Birds")))),
  
  tags$div( 
    class = "category-column",
    tags$a(href = "posts.html#category:Multispecies",
      tags$img(
        href = "posts.html#category:Multispecies",
        src = "images/vectors/platypus.svg",
        class = "category-image sage",
        style = "width: 80%;"
  )),
  tags$p(
    tags$h3(style = "text-align:center",
      tags$a(href = "posts.html#category:Multispecies", "Multispecies"))))
  
  )
```

:::

<center> <h1>We Value</h1> </center>

```{r, layout="l-screen-inset", echo = FALSE}
# find icons at https://fontawesome.com/v5.15/icons?d=gallery&p=2

tags$div(class = "values-row",
         
create_values_box1(
  value = "\   Openness",
  icon = "fas fa-book-open",
  text = "Data are most useful when they are widely available and easy to use. We try to encourage the sharing of tools that make data from the Atlas of Living Australia more open and useful for everyone"
),

create_values_box2(
  value = "\   Scientific Transparency",
  icon = "fas fa-atom",
  text = "Transparency is necessary for reproducible science. We encourage that decisions, methods and deviations in our workflow are clear and transparent from the planning phase, to the retrieval and analysis of data, to the final output"
),

create_values_box3(
  value = "\   Robust methods",
  icon = "far fa-chart-bar",
  text = "No method or analytic procedure is perfect. We value consideration for strengths and limitations of each method or analysis to help choose the methods that provide robust, reliable results"
)

)
```
