<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.306">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Amanda Buyan,Dax Kellie">
<meta name="dcterms.date" content="2023-11-23">

<title>Adding Buffers to Shapefiles</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Adding_Buffers_Shapefiles_files/libs/clipboard/clipboard.min.js"></script>
<script src="Adding_Buffers_Shapefiles_files/libs/quarto-html/quarto.js"></script>
<script src="Adding_Buffers_Shapefiles_files/libs/quarto-html/popper.min.js"></script>
<script src="Adding_Buffers_Shapefiles_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Adding_Buffers_Shapefiles_files/libs/quarto-html/anchor.min.js"></script>
<link href="Adding_Buffers_Shapefiles_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Adding_Buffers_Shapefiles_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Adding_Buffers_Shapefiles_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Adding_Buffers_Shapefiles_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Adding_Buffers_Shapefiles_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="style.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Adding Buffers to Shapefiles</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Amanda Buyan,Dax Kellie </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 23, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>Adding buffers to shapefiles can be good when you are searching an area, such as a Local Government Area, a township, or a custom shapefile given to you by a researcher or client. This is because there may be species that you are interested in that don’t occur in the boundaries, but in the edges of the shape. To capture the area around the edges, one needs to add a buffer to the shape. In this post, we will use <code>galah-python</code>, <code>geopandas</code>, <code>shapely</code>, and <code>matplotlib</code> (for visualisation purposes) to add buffers around shapefiles, as well as get occurrences within the shape. We will also explain what is going on when you use the <code>buffer</code> argument in <code>atlas_species()</code> and <code>atlas_occurrences()</code>.</p>
<section id="adding-the-buffer-to-the-shapefile" class="level2">
<h2 class="anchored" data-anchor-id="adding-the-buffer-to-the-shapefile">Adding the buffer to the shapefile</h2>
<p>For those who want more control, and to understand what the <code>buffer</code> argument in <code>galah-python</code> will do to your shapefile, we will take you through step by step on how to add a buffer to your shape. We will use the same example as we did in the <a href="labs.ala.org.au">species list post</a>, but this time we will add a buffer to the shape file.</p>
<p>First, we will read in the Local Government Areas (LGAs) shapefile that we did in the previous post. Then, we will select the Yass Valley again as our example (though users may want to select another LGA they are interested in).</p>
<div class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> geopandas <span class="im">as</span> gpd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>LGAs_2023 <span class="op">=</span> gpd.read_file(<span class="st">"LGA_2023_AUST_GDA2020.shp"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>NSW <span class="op">=</span> LGAs_2023[LGAs_2023[<span class="st">'STE_NAME21'</span>] <span class="op">==</span> <span class="st">"New South Wales"</span>]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry <span class="op">=</span> NSW[NSW[<span class="st">'LGA_NAME23'</span>] <span class="op">==</span> <span class="st">"Yass Valley"</span>]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry.plot(edgecolor <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>, facecolor <span class="op">=</span> <span class="st">"white"</span>, figsize <span class="op">=</span> (<span class="dv">12</span>,<span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<pre><code>&lt;Axes: &gt;</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Adding_Buffers_Shapefiles_files/figure-html/cell-2-output-2.png" width="419" height="415"></p>
</div>
</div>
<p>Now that we have the geometry, we can begin the process of adding a buffer region. Adding a buffer using the <code>shapely</code> package is straightforward; however, we will have to remind ourselves of the discussion about Coordinate Reference Systems (CRSs) in the <a href="labs.ala.org.au">species list post</a>. Essentially, there are many ways to represent two-dimensional coordinates on the three-dimensional earth. The most common is in degrees latitude and degrees longitude. Another way is to use meters, which is what we will need for this buffering exercise, as the buffers can only be added in meter units. Those in Australia will likely use the Australian Albers CRS, which has the EPSG code 3577. Those in other countries may wish to use something different, though the only requirement is it has to be in meters. To change the CRS, you will need to use the <code>to_crs</code> function with the correct EPSG code.</p>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import libraries you need</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> shapely</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib <span class="im">import</span> pyplot <span class="im">as</span> plt</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># change geometry to meters</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry_meters <span class="op">=</span> yass_valley_geometry.to_crs(<span class="dv">3577</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot results for comparison</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>plt1, ax1 <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>, figsize <span class="op">=</span> (<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>x_deg,y_deg<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>].exterior.xy</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>ax1[<span class="dv">0</span>].plot(x_deg,y_deg, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>ax1[<span class="dv">0</span>].set_title(<span class="st">"Degrees"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>x_m,y_m<span class="op">=</span>yass_valley_geometry_meters[<span class="st">"geometry"</span>][<span class="dv">127</span>].exterior.xy</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>ax1[<span class="dv">1</span>].plot(x_m,y_m, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>ax1[<span class="dv">1</span>].set_title(<span class="st">"Meters"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>plt1.suptitle(<span class="st">"Yass Valley"</span>,size<span class="op">=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>Text(0.5, 0.98, 'Yass Valley')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Adding_Buffers_Shapefiles_files/figure-html/cell-3-output-2.png" width="813" height="476"></p>
</div>
</div>
<p>We can see that the shape hasn’t changed, only the units in which they are represented. Now, we will add the buffer in units of meters. We will be adding a 10km buffer as an example.</p>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add buffer</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry_meters_buffer <span class="op">=</span> yass_valley_geometry_meters.<span class="bu">buffer</span>(<span class="dv">10000</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># visualise the object for plotting</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry_meters_buffer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<pre><code>127    POLYGON ((1489171.294 -3942142.933, 1489244.41...
dtype: geometry</code></pre>
</div>
</div>
<p>Now, we will plot the shape to see how the buffered shapefile looks in comparison to the original shapefile.</p>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>plt2, ax2 <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>, figsize <span class="op">=</span> (<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>x_deg,y_deg<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>].exterior.xy</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>ax2[<span class="dv">0</span>].plot(x_deg,y_deg, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>ax2[<span class="dv">0</span>].set_title(<span class="st">"Degrees"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>x_mb,y_mb<span class="op">=</span>yass_valley_geometry_meters_buffer[<span class="dv">127</span>].exterior.xy</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>ax2[<span class="dv">1</span>].plot(x_mb,y_mb, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>ax2[<span class="dv">1</span>].set_title(<span class="st">"Meters With Buffer"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>plt2.suptitle(<span class="st">"Yass Valley"</span>,size<span class="op">=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="24">
<pre><code>Text(0.5, 0.98, 'Yass Valley')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Adding_Buffers_Shapefiles_files/figure-html/cell-5-output-2.png" width="813" height="476"></p>
</div>
</div>
<p>There is one last thing to do before we use the shapefile to get occurrences and species lists: change the Coordinate Reference System back to one that is based on degrees latitude and longitude. To do this, we will run the <code>to_crs()</code> function again on our buffered shapefile.</p>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry_degrees_buffer <span class="op">=</span> yass_valley_geometry_meters_buffer.to_crs(<span class="dv">4326</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>yass_valley_geometry_degrees_buffer</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="25">
<pre><code>127    POLYGON ((148.43779 -35.21658, 148.43816 -35.2...
dtype: geometry</code></pre>
</div>
</div>
<p>Now, we will plot the shapes for posterity.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>plt3, ax3 <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>, figsize <span class="op">=</span> (<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>x_deg,y_deg<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>].exterior.xy</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">0</span>].plot(x_deg,y_deg, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">0</span>].set_title(<span class="st">"Degrees"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>x_mb,y_mb<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>].exterior.xy</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">1</span>].plot(x_mb,y_mb, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">1</span>].set_title(<span class="st">"Degrees With Buffer"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>plt3.suptitle(<span class="st">"Yass Valley"</span>,size<span class="op">=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>Text(0.5, 0.98, 'Yass Valley')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Adding_Buffers_Shapefiles_files/figure-html/cell-7-output-2.png" width="813" height="459"></p>
</div>
</div>
</section>
<section id="getting-counts-occurrences-and-a-species-list-in-the-buffered-shapefile" class="level2">
<h2 class="anchored" data-anchor-id="getting-counts-occurrences-and-a-species-list-in-the-buffered-shapefile">Getting counts, occurrences and a species list in the buffered shapefile</h2>
<p>Now that we have a buffered shapefile, we can start to get an idea of how many occurrences of species there are, where they are and a breakdown by type of species, including cross referencing this with species lists for the year 2023. This is an exercise in case one needs to do yearly reports, but you can always add more/different filters by finding them through the lookup function <code>show_all()</code>.</p>
<p>First, we will get an approximate count of how many counts are in the original shape versus the buffered shape.</p>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> galah</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>galah.atlas_counts(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="27">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">totalRecords</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10987</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> galah</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>galah.atlas_counts(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">totalRecords</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>56392</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We know that there are less than 5 millino records, so we can easily get the occurrence records of all species in the Yass Valley in the year 2023.</p>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>galah.galah_config(email <span class="op">=</span> <span class="st">"amanda.buyan@csiro.au"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>yass_valley_occurrences <span class="op">=</span> galah.atlas_occurrences(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>yass_valley_occurrences_buffer <span class="op">=</span> galah.atlas_occurrences(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(yass_valley_occurrences.shape)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(yass_valley_occurrences_buffer.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(10987, 55)
(56392, 55)</code></pre>
</div>
</div>
<p>By printing the shape of the data frames, we can see that the number of rows corresponds to the number of counts we got using <code>atlas_counts()</code>.</p>
<p>Now, to show you the difference in where these occurrences are, and how much the buffer picks up around the boundaries, we will plot them side by side.</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>plt3, ax3 <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">2</span>, figsize <span class="op">=</span> (<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>x_deg,y_deg<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>].exterior.xy</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">0</span>].plot(x_deg,y_deg, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">0</span>].scatter(yass_valley_occurrences[<span class="st">"decimalLongitude"</span>],yass_valley_occurrences[<span class="st">"decimalLatitude"</span>],color <span class="op">=</span> <span class="st">"blue"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">0</span>].set_title(<span class="st">"Degrees"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>x_mb,y_mb<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>].exterior.xy</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">1</span>].plot(x_mb,y_mb, color <span class="op">=</span> <span class="st">"#5A5A5A"</span>, linewidth <span class="op">=</span> <span class="fl">0.5</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">1</span>].scatter(yass_valley_occurrences_buffer[<span class="st">"decimalLongitude"</span>],yass_valley_occurrences_buffer[<span class="st">"decimalLatitude"</span>],color <span class="op">=</span> <span class="st">"blue"</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>ax3[<span class="dv">1</span>].set_title(<span class="st">"Degrees With Buffer"</span>,size<span class="op">=</span><span class="dv">12</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>plt3.suptitle(<span class="st">"Yass Valley"</span>,size<span class="op">=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>Text(0.5, 0.98, 'Yass Valley')</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="Adding_Buffers_Shapefiles_files/figure-html/cell-11-output-2.png" width="813" height="459"></p>
</div>
</div>
<p>To get a breakdown of what species are in the area, we can run <code>atlas_species()</code> to get the list.</p>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Species Name</th>
<th data-quarto-table-cell-role="th">Scientific Name Authorship</th>
<th data-quarto-table-cell-role="th">Taxon Rank</th>
<th data-quarto-table-cell-role="th">Kingdom</th>
<th data-quarto-table-cell-role="th">Phylum</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Order</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Genus</th>
<th data-quarto-table-cell-role="th">Vernacular Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>https://biodiversity.org.au/afd/taxa/5291343e-...</td>
<td>Gymnorhina tibicen</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Artamidae</td>
<td>Gymnorhina</td>
<td>Australian Magpie</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>https://biodiversity.org.au/afd/taxa/2c33a1fd-...</td>
<td>Cacatua (Cacatua) galerita</td>
<td>(Latham, 1790)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Cacatuidae</td>
<td>Cacatua</td>
<td>Sulphur-crested Cockatoo</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>https://biodiversity.org.au/afd/taxa/5e0f496f-...</td>
<td>Platycercus (Platycercus) elegans</td>
<td>(Gmelin, 1788)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Psittacidae</td>
<td>Platycercus</td>
<td>Crimson Rosella</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>https://biodiversity.org.au/afd/taxa/ce17b284-...</td>
<td>Grallina cyanoleuca</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Monarchidae</td>
<td>Grallina</td>
<td>Magpie-lark</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>https://biodiversity.org.au/afd/taxa/760401df-...</td>
<td>Malurus (Malurus) cyaneus</td>
<td>(Ellis, 1782)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Maluridae</td>
<td>Malurus</td>
<td>Superb Fairy-wren</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1984</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Pterostylis mutica</td>
<td>R.Br.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Pterostylis</td>
<td>Midget Greenhood</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1985</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Pterostylis rubescens</td>
<td>(D.L.Jones) G.N.Backh.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Pterostylis</td>
<td>Inland Red-tip Greenhood</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1986</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Thelymitra ixioides</td>
<td>Sw.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Thelymitra</td>
<td>Dotted Sun Orchid</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1987</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Thynninorchis huntiana</td>
<td>(F.Muell.) D.L.Jones &amp; M.A.Clem.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Thynninorchis</td>
<td>Common Elbow Orchid</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1988</td>
<td>https://id.biodiversity.org.au/taxon/ausmoss/1...</td>
<td>Thuidiopsis sparsa</td>
<td>(Hook.f. &amp; Wilson) Broth.</td>
<td>species</td>
<td>Plantae</td>
<td>Bryophyta</td>
<td>Bryopsida</td>
<td>Hypnales</td>
<td>Thuidiaceae</td>
<td>Thuidiopsis</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>1989 rows × 11 columns</p>
</div>
</div>
</div>
<p>To cross reference it with the sensitive species list for NSW (see previous article for more details), we can add the argument <code>species_list_uid=dr650</code>.</p>
<div class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="32">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Species Name</th>
<th data-quarto-table-cell-role="th">Scientific Name Authorship</th>
<th data-quarto-table-cell-role="th">Taxon Rank</th>
<th data-quarto-table-cell-role="th">Kingdom</th>
<th data-quarto-table-cell-role="th">Phylum</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Order</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Genus</th>
<th data-quarto-table-cell-role="th">Vernacular Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>https://biodiversity.org.au/afd/taxa/6c646af8-...</td>
<td>Callocephalon fimbriatum</td>
<td>(Grant, 1803)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Cacatuidae</td>
<td>Callocephalon</td>
<td>Gang-gang Cockatoo</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>https://biodiversity.org.au/afd/taxa/46fca72f-...</td>
<td>Polytelis swainsonii</td>
<td>(Desmarest, 1826)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Psittacidae</td>
<td>Polytelis</td>
<td>Superb Parrot</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>https://biodiversity.org.au/afd/taxa/a3e5376b-...</td>
<td>Petroica (Petroica) boodang</td>
<td>(Lesson, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Scarlet Robin</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>https://biodiversity.org.au/afd/taxa/11036a27-...</td>
<td>Irediparra gallinacea</td>
<td>(Temminck, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Jacanidae</td>
<td>Irediparra</td>
<td>Comb-crested Jacana</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>https://biodiversity.org.au/afd/taxa/8bf4b8b0-...</td>
<td>Daphoenositta (Neositta) chrysoptera</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Neosittidae</td>
<td>Daphoenositta</td>
<td>Varied Sittella</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>https://biodiversity.org.au/afd/taxa/fe74e658-...</td>
<td>Petroica (Littlera) phoenicea</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Flame Robin</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>https://biodiversity.org.au/afd/taxa/cc5315bf-...</td>
<td>Pseudophryne pengilleyi</td>
<td>Wells &amp; Wellington, 1985</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Myobatrachidae</td>
<td>Pseudophryne</td>
<td>Northern Corroboree Frog</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>https://biodiversity.org.au/afd/taxa/2063bf6d-...</td>
<td>Pachycephala (Timixos) olivacea</td>
<td>Vigors &amp; Horsfield, 1827</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Pachycephalidae</td>
<td>Pachycephala</td>
<td>Olive Whistler</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>https://biodiversity.org.au/afd/taxa/6e872b58-...</td>
<td>Stagonopleura (Stagonopleura) guttata</td>
<td>(Shaw, 1796)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Estrildidae</td>
<td>Stagonopleura</td>
<td>Diamond Firetail</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>https://biodiversity.org.au/afd/taxa/b47a4ecd-...</td>
<td>Hieraaetus (Hieraaetus) morphnoides</td>
<td>(Gould, 1841)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Hieraaetus</td>
<td>Little Eagle</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>https://biodiversity.org.au/afd/taxa/cd4e3b1b-...</td>
<td>Burhinus (Burhinus) grallarius</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Burhinidae</td>
<td>Burhinus</td>
<td>Bush Stone-curlew</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>https://biodiversity.org.au/afd/taxa/19c9bfdf-...</td>
<td>Bettongia gaimardi</td>
<td>(Desmarest, 1822)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Potoroidae</td>
<td>Bettongia</td>
<td>Tasmanian Bettong</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>https://biodiversity.org.au/afd/taxa/d1c5dee0-...</td>
<td>Ninox (Rhabdoglaux) strenua</td>
<td>(Gould, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Strigiformes</td>
<td>Strigidae</td>
<td>Ninox</td>
<td>Powerful Owl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>https://biodiversity.org.au/afd/taxa/dc420306-...</td>
<td>Haliaeetus (Pontoaetus) leucogaster</td>
<td>(Gmelin, 1788)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Haliaeetus</td>
<td>White-bellied Sea-eagle</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>https://biodiversity.org.au/afd/taxa/52149285-...</td>
<td>Dasyurus viverrinus</td>
<td>(Shaw, 1800)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Dasyuromorphia</td>
<td>Dasyuridae</td>
<td>Dasyurus</td>
<td>Eastern Quoll</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>https://biodiversity.org.au/afd/taxa/a51dca29-...</td>
<td>Synemon plana</td>
<td>Walker, 1854</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Lepidoptera</td>
<td>Castniidae</td>
<td>Synemon</td>
<td>Golden Sun Moth</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>https://biodiversity.org.au/afd/taxa/c95af018-...</td>
<td>Epthianura (Epthianura) albifrons</td>
<td>(Jardine &amp; Selby, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Meliphagidae</td>
<td>Epthianura</td>
<td>White-fronted Chat</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>https://id.biodiversity.org.au/node/apni/2910323</td>
<td>Ammobium craspedioides</td>
<td>Benth.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Ammobium</td>
<td>Yass Daisy</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>https://id.biodiversity.org.au/node/apni/2918079</td>
<td>Wilsonia rotundifolia</td>
<td>Hook.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Solanales</td>
<td>Convolvulaceae</td>
<td>Wilsonia</td>
<td>Roundleaf Wilsonia</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>https://biodiversity.org.au/afd/taxa/694a8fde-...</td>
<td>Circus assimilis</td>
<td>Jardine &amp; Selby, 1828</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Circus</td>
<td>Spotted Harrier</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>https://biodiversity.org.au/afd/taxa/32f9229c-...</td>
<td>Oxyura australis</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Anseriformes</td>
<td>Anatidae</td>
<td>Oxyura</td>
<td>Blue-billed Duck</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>https://id.biodiversity.org.au/taxon/apni/5128...</td>
<td>Leucochrysum albicans</td>
<td>(A.Cunn.) Paul G.Wilson</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Leucochrysum</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>https://biodiversity.org.au/afd/taxa/dba78701-...</td>
<td>Botaurus poiciloptilus</td>
<td>(Wagler, 1827)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Ciconiiformes</td>
<td>Ardeidae</td>
<td>Botaurus</td>
<td>Australasian Bittern</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>https://id.biodiversity.org.au/node/apni/2920809</td>
<td>Eucalyptus pumila</td>
<td>Cambage</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Pokolbin Mallee</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>https://id.biodiversity.org.au/node/apni/7062437</td>
<td>Rutidosis leptorhynchoides</td>
<td>F.Muell.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Rutidosis</td>
<td>Button Wrinklewort</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25</td>
<td>https://id.biodiversity.org.au/taxon/apni/5129...</td>
<td>Eucalyptus radiata</td>
<td>Sieber ex DC.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Narrow-leaved Peppermint</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>https://biodiversity.org.au/afd/taxa/0aa4d63d-...</td>
<td>Keyacris scurra</td>
<td>(Rehn, 1952)</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Orthoptera</td>
<td>Morabidae</td>
<td>Keyacris</td>
<td>Key's Matchstick Grasshopper</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>https://biodiversity.org.au/afd/taxa/1b653e0c-...</td>
<td>Petaurus norfolcensis</td>
<td>(Kerr, 1792)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Petauridae</td>
<td>Petaurus</td>
<td>Squirrel Glider</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">28</td>
<td>https://biodiversity.org.au/afd/taxa/320aeab1-...</td>
<td>Artamus (Angroyan) cyanopterus</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Artamidae</td>
<td>Artamus</td>
<td>Dusky Woodswallow</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">29</td>
<td>https://biodiversity.org.au/afd/taxa/5557cf29-...</td>
<td>Litoria verreauxii</td>
<td>(DumÃ©ril, 1853)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Hylidae</td>
<td>Litoria</td>
<td>Verreaux's Frog</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>https://biodiversity.org.au/afd/taxa/e9d6fbbd-...</td>
<td>Phascolarctos cinereus</td>
<td>(Goldfuss, 1817)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Phascolarctidae</td>
<td>Phascolarctos</td>
<td>Koala</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To add the nuber of counts of each species, you can add the <code>counts=True</code> argument.</p>
<div class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>],counts<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Species Name</th>
<th data-quarto-table-cell-role="th">Scientific Name Authorship</th>
<th data-quarto-table-cell-role="th">Taxon Rank</th>
<th data-quarto-table-cell-role="th">Kingdom</th>
<th data-quarto-table-cell-role="th">Phylum</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Order</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Genus</th>
<th data-quarto-table-cell-role="th">Vernacular Name</th>
<th data-quarto-table-cell-role="th">Number of records</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>https://biodiversity.org.au/afd/taxa/6c646af8-...</td>
<td>Callocephalon fimbriatum</td>
<td>(Grant, 1803)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Cacatuidae</td>
<td>Callocephalon</td>
<td>Gang-gang Cockatoo</td>
<td>265</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>https://biodiversity.org.au/afd/taxa/46fca72f-...</td>
<td>Polytelis swainsonii</td>
<td>(Desmarest, 1826)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Psittacidae</td>
<td>Polytelis</td>
<td>Superb Parrot</td>
<td>241</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>https://biodiversity.org.au/afd/taxa/a3e5376b-...</td>
<td>Petroica (Petroica) boodang</td>
<td>(Lesson, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Scarlet Robin</td>
<td>151</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>https://biodiversity.org.au/afd/taxa/11036a27-...</td>
<td>Irediparra gallinacea</td>
<td>(Temminck, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Jacanidae</td>
<td>Irediparra</td>
<td>Comb-crested Jacana</td>
<td>81</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>https://biodiversity.org.au/afd/taxa/8bf4b8b0-...</td>
<td>Daphoenositta (Neositta) chrysoptera</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Neosittidae</td>
<td>Daphoenositta</td>
<td>Varied Sittella</td>
<td>59</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>https://biodiversity.org.au/afd/taxa/fe74e658-...</td>
<td>Petroica (Littlera) phoenicea</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Flame Robin</td>
<td>45</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>https://biodiversity.org.au/afd/taxa/cc5315bf-...</td>
<td>Pseudophryne pengilleyi</td>
<td>Wells &amp; Wellington, 1985</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Myobatrachidae</td>
<td>Pseudophryne</td>
<td>Northern Corroboree Frog</td>
<td>33</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>https://biodiversity.org.au/afd/taxa/2063bf6d-...</td>
<td>Pachycephala (Timixos) olivacea</td>
<td>Vigors &amp; Horsfield, 1827</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Pachycephalidae</td>
<td>Pachycephala</td>
<td>Olive Whistler</td>
<td>28</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>https://biodiversity.org.au/afd/taxa/6e872b58-...</td>
<td>Stagonopleura (Stagonopleura) guttata</td>
<td>(Shaw, 1796)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Estrildidae</td>
<td>Stagonopleura</td>
<td>Diamond Firetail</td>
<td>28</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>https://biodiversity.org.au/afd/taxa/b47a4ecd-...</td>
<td>Hieraaetus (Hieraaetus) morphnoides</td>
<td>(Gould, 1841)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Hieraaetus</td>
<td>Little Eagle</td>
<td>23</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>https://biodiversity.org.au/afd/taxa/cd4e3b1b-...</td>
<td>Burhinus (Burhinus) grallarius</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Burhinidae</td>
<td>Burhinus</td>
<td>Bush Stone-curlew</td>
<td>13</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>https://biodiversity.org.au/afd/taxa/19c9bfdf-...</td>
<td>Bettongia gaimardi</td>
<td>(Desmarest, 1822)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Potoroidae</td>
<td>Bettongia</td>
<td>Tasmanian Bettong</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>https://biodiversity.org.au/afd/taxa/d1c5dee0-...</td>
<td>Ninox (Rhabdoglaux) strenua</td>
<td>(Gould, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Strigiformes</td>
<td>Strigidae</td>
<td>Ninox</td>
<td>Powerful Owl</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>https://biodiversity.org.au/afd/taxa/dc420306-...</td>
<td>Haliaeetus (Pontoaetus) leucogaster</td>
<td>(Gmelin, 1788)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Haliaeetus</td>
<td>White-bellied Sea-eagle</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>https://biodiversity.org.au/afd/taxa/52149285-...</td>
<td>Dasyurus viverrinus</td>
<td>(Shaw, 1800)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Dasyuromorphia</td>
<td>Dasyuridae</td>
<td>Dasyurus</td>
<td>Eastern Quoll</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>https://biodiversity.org.au/afd/taxa/a51dca29-...</td>
<td>Synemon plana</td>
<td>Walker, 1854</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Lepidoptera</td>
<td>Castniidae</td>
<td>Synemon</td>
<td>Golden Sun Moth</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>https://biodiversity.org.au/afd/taxa/c95af018-...</td>
<td>Epthianura (Epthianura) albifrons</td>
<td>(Jardine &amp; Selby, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Meliphagidae</td>
<td>Epthianura</td>
<td>White-fronted Chat</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>https://id.biodiversity.org.au/node/apni/2910323</td>
<td>Ammobium craspedioides</td>
<td>Benth.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Ammobium</td>
<td>Yass Daisy</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>https://id.biodiversity.org.au/node/apni/2918079</td>
<td>Wilsonia rotundifolia</td>
<td>Hook.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Solanales</td>
<td>Convolvulaceae</td>
<td>Wilsonia</td>
<td>Roundleaf Wilsonia</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>https://biodiversity.org.au/afd/taxa/694a8fde-...</td>
<td>Circus assimilis</td>
<td>Jardine &amp; Selby, 1828</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Circus</td>
<td>Spotted Harrier</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>https://biodiversity.org.au/afd/taxa/32f9229c-...</td>
<td>Oxyura australis</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Anseriformes</td>
<td>Anatidae</td>
<td>Oxyura</td>
<td>Blue-billed Duck</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>https://id.biodiversity.org.au/taxon/apni/5128...</td>
<td>Leucochrysum albicans</td>
<td>(A.Cunn.) Paul G.Wilson</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Leucochrysum</td>
<td>NaN</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>https://biodiversity.org.au/afd/taxa/dba78701-...</td>
<td>Botaurus poiciloptilus</td>
<td>(Wagler, 1827)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Ciconiiformes</td>
<td>Ardeidae</td>
<td>Botaurus</td>
<td>Australasian Bittern</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>https://id.biodiversity.org.au/node/apni/2920809</td>
<td>Eucalyptus pumila</td>
<td>Cambage</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Pokolbin Mallee</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>https://id.biodiversity.org.au/node/apni/7062437</td>
<td>Rutidosis leptorhynchoides</td>
<td>F.Muell.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Rutidosis</td>
<td>Button Wrinklewort</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25</td>
<td>https://id.biodiversity.org.au/taxon/apni/5129...</td>
<td>Eucalyptus radiata</td>
<td>Sieber ex DC.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Narrow-leaved Peppermint</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>https://biodiversity.org.au/afd/taxa/0aa4d63d-...</td>
<td>Keyacris scurra</td>
<td>(Rehn, 1952)</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Orthoptera</td>
<td>Morabidae</td>
<td>Keyacris</td>
<td>Key's Matchstick Grasshopper</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>https://biodiversity.org.au/afd/taxa/1b653e0c-...</td>
<td>Petaurus norfolcensis</td>
<td>(Kerr, 1792)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Petauridae</td>
<td>Petaurus</td>
<td>Squirrel Glider</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">28</td>
<td>https://biodiversity.org.au/afd/taxa/320aeab1-...</td>
<td>Artamus (Angroyan) cyanopterus</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Artamidae</td>
<td>Artamus</td>
<td>Dusky Woodswallow</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">29</td>
<td>https://biodiversity.org.au/afd/taxa/5557cf29-...</td>
<td>Litoria verreauxii</td>
<td>(DumÃ©ril, 1853)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Hylidae</td>
<td>Litoria</td>
<td>Verreaux's Frog</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>https://biodiversity.org.au/afd/taxa/e9d6fbbd-...</td>
<td>Phascolarctos cinereus</td>
<td>(Goldfuss, 1817)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Phascolarctidae</td>
<td>Phascolarctos</td>
<td>Koala</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Now, if you want to save this data to a file, you can use the <code>to_csv</code> function in <code>pandas</code>.</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species <span class="op">=</span> galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>])</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species_counts <span class="op">=</span> galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>],counts<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species.to_csv(<span class="st">"yass_valley_species_buffer_sensitive_species.csv"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species_counts.to_csv(<span class="st">"yass_valley_species_buffer_sensitive_species_counts.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="using-the-buffer-argument-with-a-shapefile" class="level2">
<h2 class="anchored" data-anchor-id="using-the-buffer-argument-with-a-shapefile">Using the <code>buffer</code> argument with a shapefile</h2>
<p>If you would prefer to not add a buffer manually, but instead have <code>galah-python</code> do it for you, there is an option called <code>buffer</code>, as well as <code>crs_deg</code> and <code>crs_meters</code>. What <code>galah-python</code> does is what we have showed in this post, but the user doesn’t see it. The main difference is that the <code>buffer</code> argument takes a number in units of kilometers, rather than meters. Below is how you would repeat the above mapping, just using <code>galah-python</code> to do the buffering instead. The Coordinate Reference Systems are provided for posterity and for clarity, though those are the defaults set in <code>galah-python</code>.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> galah</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>galah.atlas_counts(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">totalRecords</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>10987</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> galah</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>galah.atlas_counts(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>,<span class="bu">buffer</span><span class="op">=</span><span class="dv">10</span>,crs_deg<span class="op">=</span><span class="dv">4326</span>,crs_meters<span class="op">=</span><span class="dv">3577</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">totalRecords</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>56392</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>We can see that 10987 and 56392 are the same counts we calculated above using our manually buffered shapefile. Now, we can get the occurrences.</p>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>galah.galah_config(email <span class="op">=</span> <span class="st">"amanda.buyan@csiro.au"</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>yass_valley_occurrences <span class="op">=</span> galah.atlas_occurrences(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>yass_valley_occurrences_buffer <span class="op">=</span> galah.atlas_occurrences(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>,<span class="bu">buffer</span><span class="op">=</span><span class="dv">10</span>,crs_deg<span class="op">=</span><span class="dv">4326</span>,crs_meters<span class="op">=</span><span class="dv">3577</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(yass_valley_occurrences.shape)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(yass_valley_occurrences_buffer.shape)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(10987, 55)
(56392, 55)</code></pre>
</div>
</div>
<p>We can see that X and Y are the same counts we calculated above using our manually buffered shapefile. Now, we can get species lists.</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],filters<span class="op">=</span><span class="st">"year=2023"</span>,<span class="bu">buffer</span><span class="op">=</span><span class="dv">10</span>,crs_deg<span class="op">=</span><span class="dv">4326</span>,crs_meters<span class="op">=</span><span class="dv">3577</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Species Name</th>
<th data-quarto-table-cell-role="th">Scientific Name Authorship</th>
<th data-quarto-table-cell-role="th">Taxon Rank</th>
<th data-quarto-table-cell-role="th">Kingdom</th>
<th data-quarto-table-cell-role="th">Phylum</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Order</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Genus</th>
<th data-quarto-table-cell-role="th">Vernacular Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>https://biodiversity.org.au/afd/taxa/5291343e-...</td>
<td>Gymnorhina tibicen</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Artamidae</td>
<td>Gymnorhina</td>
<td>Australian Magpie</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>https://biodiversity.org.au/afd/taxa/2c33a1fd-...</td>
<td>Cacatua (Cacatua) galerita</td>
<td>(Latham, 1790)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Cacatuidae</td>
<td>Cacatua</td>
<td>Sulphur-crested Cockatoo</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>https://biodiversity.org.au/afd/taxa/5e0f496f-...</td>
<td>Platycercus (Platycercus) elegans</td>
<td>(Gmelin, 1788)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Psittacidae</td>
<td>Platycercus</td>
<td>Crimson Rosella</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>https://biodiversity.org.au/afd/taxa/ce17b284-...</td>
<td>Grallina cyanoleuca</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Monarchidae</td>
<td>Grallina</td>
<td>Magpie-lark</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>https://biodiversity.org.au/afd/taxa/760401df-...</td>
<td>Malurus (Malurus) cyaneus</td>
<td>(Ellis, 1782)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Maluridae</td>
<td>Malurus</td>
<td>Superb Fairy-wren</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1984</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Pterostylis mutica</td>
<td>R.Br.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Pterostylis</td>
<td>Midget Greenhood</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1985</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Pterostylis rubescens</td>
<td>(D.L.Jones) G.N.Backh.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Pterostylis</td>
<td>Inland Red-tip Greenhood</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1986</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Thelymitra ixioides</td>
<td>Sw.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Thelymitra</td>
<td>Dotted Sun Orchid</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1987</td>
<td>https://id.biodiversity.org.au/taxon/apni/5141...</td>
<td>Thynninorchis huntiana</td>
<td>(F.Muell.) D.L.Jones &amp; M.A.Clem.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asparagales</td>
<td>Orchidaceae</td>
<td>Thynninorchis</td>
<td>Common Elbow Orchid</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1988</td>
<td>https://id.biodiversity.org.au/taxon/ausmoss/1...</td>
<td>Thuidiopsis sparsa</td>
<td>(Hook.f. &amp; Wilson) Broth.</td>
<td>species</td>
<td>Plantae</td>
<td>Bryophyta</td>
<td>Bryopsida</td>
<td>Hypnales</td>
<td>Thuidiaceae</td>
<td>Thuidiopsis</td>
<td>NaN</td>
</tr>
</tbody>
</table>

<p>1989 rows × 11 columns</p>
</div>
</div>
</div>
<p>To cross reference it with the sensitive species list for NSW (see previous article for more details), we can add the argument <code>species_list_uid=dr650</code>.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],<span class="bu">buffer</span><span class="op">=</span><span class="dv">10</span>,crs_deg<span class="op">=</span><span class="dv">4326</span>,crs_meters<span class="op">=</span><span class="dv">3577</span>,filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="39">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Species Name</th>
<th data-quarto-table-cell-role="th">Scientific Name Authorship</th>
<th data-quarto-table-cell-role="th">Taxon Rank</th>
<th data-quarto-table-cell-role="th">Kingdom</th>
<th data-quarto-table-cell-role="th">Phylum</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Order</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Genus</th>
<th data-quarto-table-cell-role="th">Vernacular Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>https://biodiversity.org.au/afd/taxa/6c646af8-...</td>
<td>Callocephalon fimbriatum</td>
<td>(Grant, 1803)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Cacatuidae</td>
<td>Callocephalon</td>
<td>Gang-gang Cockatoo</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>https://biodiversity.org.au/afd/taxa/46fca72f-...</td>
<td>Polytelis swainsonii</td>
<td>(Desmarest, 1826)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Psittacidae</td>
<td>Polytelis</td>
<td>Superb Parrot</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>https://biodiversity.org.au/afd/taxa/a3e5376b-...</td>
<td>Petroica (Petroica) boodang</td>
<td>(Lesson, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Scarlet Robin</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>https://biodiversity.org.au/afd/taxa/11036a27-...</td>
<td>Irediparra gallinacea</td>
<td>(Temminck, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Jacanidae</td>
<td>Irediparra</td>
<td>Comb-crested Jacana</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>https://biodiversity.org.au/afd/taxa/8bf4b8b0-...</td>
<td>Daphoenositta (Neositta) chrysoptera</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Neosittidae</td>
<td>Daphoenositta</td>
<td>Varied Sittella</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>https://biodiversity.org.au/afd/taxa/fe74e658-...</td>
<td>Petroica (Littlera) phoenicea</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Flame Robin</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>https://biodiversity.org.au/afd/taxa/cc5315bf-...</td>
<td>Pseudophryne pengilleyi</td>
<td>Wells &amp; Wellington, 1985</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Myobatrachidae</td>
<td>Pseudophryne</td>
<td>Northern Corroboree Frog</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>https://biodiversity.org.au/afd/taxa/2063bf6d-...</td>
<td>Pachycephala (Timixos) olivacea</td>
<td>Vigors &amp; Horsfield, 1827</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Pachycephalidae</td>
<td>Pachycephala</td>
<td>Olive Whistler</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>https://biodiversity.org.au/afd/taxa/6e872b58-...</td>
<td>Stagonopleura (Stagonopleura) guttata</td>
<td>(Shaw, 1796)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Estrildidae</td>
<td>Stagonopleura</td>
<td>Diamond Firetail</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>https://biodiversity.org.au/afd/taxa/b47a4ecd-...</td>
<td>Hieraaetus (Hieraaetus) morphnoides</td>
<td>(Gould, 1841)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Hieraaetus</td>
<td>Little Eagle</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>https://biodiversity.org.au/afd/taxa/cd4e3b1b-...</td>
<td>Burhinus (Burhinus) grallarius</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Burhinidae</td>
<td>Burhinus</td>
<td>Bush Stone-curlew</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>https://biodiversity.org.au/afd/taxa/19c9bfdf-...</td>
<td>Bettongia gaimardi</td>
<td>(Desmarest, 1822)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Potoroidae</td>
<td>Bettongia</td>
<td>Tasmanian Bettong</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>https://biodiversity.org.au/afd/taxa/d1c5dee0-...</td>
<td>Ninox (Rhabdoglaux) strenua</td>
<td>(Gould, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Strigiformes</td>
<td>Strigidae</td>
<td>Ninox</td>
<td>Powerful Owl</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>https://biodiversity.org.au/afd/taxa/dc420306-...</td>
<td>Haliaeetus (Pontoaetus) leucogaster</td>
<td>(Gmelin, 1788)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Haliaeetus</td>
<td>White-bellied Sea-eagle</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>https://biodiversity.org.au/afd/taxa/52149285-...</td>
<td>Dasyurus viverrinus</td>
<td>(Shaw, 1800)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Dasyuromorphia</td>
<td>Dasyuridae</td>
<td>Dasyurus</td>
<td>Eastern Quoll</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>https://biodiversity.org.au/afd/taxa/a51dca29-...</td>
<td>Synemon plana</td>
<td>Walker, 1854</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Lepidoptera</td>
<td>Castniidae</td>
<td>Synemon</td>
<td>Golden Sun Moth</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>https://biodiversity.org.au/afd/taxa/c95af018-...</td>
<td>Epthianura (Epthianura) albifrons</td>
<td>(Jardine &amp; Selby, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Meliphagidae</td>
<td>Epthianura</td>
<td>White-fronted Chat</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>https://id.biodiversity.org.au/node/apni/2910323</td>
<td>Ammobium craspedioides</td>
<td>Benth.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Ammobium</td>
<td>Yass Daisy</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>https://id.biodiversity.org.au/node/apni/2918079</td>
<td>Wilsonia rotundifolia</td>
<td>Hook.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Solanales</td>
<td>Convolvulaceae</td>
<td>Wilsonia</td>
<td>Roundleaf Wilsonia</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>https://biodiversity.org.au/afd/taxa/694a8fde-...</td>
<td>Circus assimilis</td>
<td>Jardine &amp; Selby, 1828</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Circus</td>
<td>Spotted Harrier</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>https://biodiversity.org.au/afd/taxa/32f9229c-...</td>
<td>Oxyura australis</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Anseriformes</td>
<td>Anatidae</td>
<td>Oxyura</td>
<td>Blue-billed Duck</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>https://id.biodiversity.org.au/taxon/apni/5128...</td>
<td>Leucochrysum albicans</td>
<td>(A.Cunn.) Paul G.Wilson</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Leucochrysum</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>https://biodiversity.org.au/afd/taxa/dba78701-...</td>
<td>Botaurus poiciloptilus</td>
<td>(Wagler, 1827)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Ciconiiformes</td>
<td>Ardeidae</td>
<td>Botaurus</td>
<td>Australasian Bittern</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>https://id.biodiversity.org.au/node/apni/2920809</td>
<td>Eucalyptus pumila</td>
<td>Cambage</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Pokolbin Mallee</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>https://id.biodiversity.org.au/node/apni/7062437</td>
<td>Rutidosis leptorhynchoides</td>
<td>F.Muell.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Rutidosis</td>
<td>Button Wrinklewort</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25</td>
<td>https://id.biodiversity.org.au/taxon/apni/5129...</td>
<td>Eucalyptus radiata</td>
<td>Sieber ex DC.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Narrow-leaved Peppermint</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>https://biodiversity.org.au/afd/taxa/0aa4d63d-...</td>
<td>Keyacris scurra</td>
<td>(Rehn, 1952)</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Orthoptera</td>
<td>Morabidae</td>
<td>Keyacris</td>
<td>Key's Matchstick Grasshopper</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>https://biodiversity.org.au/afd/taxa/1b653e0c-...</td>
<td>Petaurus norfolcensis</td>
<td>(Kerr, 1792)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Petauridae</td>
<td>Petaurus</td>
<td>Squirrel Glider</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">28</td>
<td>https://biodiversity.org.au/afd/taxa/320aeab1-...</td>
<td>Artamus (Angroyan) cyanopterus</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Artamidae</td>
<td>Artamus</td>
<td>Dusky Woodswallow</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">29</td>
<td>https://biodiversity.org.au/afd/taxa/5557cf29-...</td>
<td>Litoria verreauxii</td>
<td>(DumÃ©ril, 1853)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Hylidae</td>
<td>Litoria</td>
<td>Verreaux's Frog</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>https://biodiversity.org.au/afd/taxa/e9d6fbbd-...</td>
<td>Phascolarctos cinereus</td>
<td>(Goldfuss, 1817)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Phascolarctidae</td>
<td>Phascolarctos</td>
<td>Koala</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>To add the nuber of counts of each species, you can add the <code>counts=True</code> argument.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry[<span class="st">"geometry"</span>][<span class="dv">127</span>],<span class="bu">buffer</span><span class="op">=</span><span class="dv">10</span>,crs_deg<span class="op">=</span><span class="dv">4326</span>,crs_meters<span class="op">=</span><span class="dv">3577</span>,filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>],counts<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<div>


<table class="dataframe table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Species</th>
<th data-quarto-table-cell-role="th">Species Name</th>
<th data-quarto-table-cell-role="th">Scientific Name Authorship</th>
<th data-quarto-table-cell-role="th">Taxon Rank</th>
<th data-quarto-table-cell-role="th">Kingdom</th>
<th data-quarto-table-cell-role="th">Phylum</th>
<th data-quarto-table-cell-role="th">Class</th>
<th data-quarto-table-cell-role="th">Order</th>
<th data-quarto-table-cell-role="th">Family</th>
<th data-quarto-table-cell-role="th">Genus</th>
<th data-quarto-table-cell-role="th">Vernacular Name</th>
<th data-quarto-table-cell-role="th">Number of records</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>https://biodiversity.org.au/afd/taxa/6c646af8-...</td>
<td>Callocephalon fimbriatum</td>
<td>(Grant, 1803)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Cacatuidae</td>
<td>Callocephalon</td>
<td>Gang-gang Cockatoo</td>
<td>265</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>https://biodiversity.org.au/afd/taxa/46fca72f-...</td>
<td>Polytelis swainsonii</td>
<td>(Desmarest, 1826)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Psittaciformes</td>
<td>Psittacidae</td>
<td>Polytelis</td>
<td>Superb Parrot</td>
<td>241</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>https://biodiversity.org.au/afd/taxa/a3e5376b-...</td>
<td>Petroica (Petroica) boodang</td>
<td>(Lesson, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Scarlet Robin</td>
<td>151</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>https://biodiversity.org.au/afd/taxa/11036a27-...</td>
<td>Irediparra gallinacea</td>
<td>(Temminck, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Jacanidae</td>
<td>Irediparra</td>
<td>Comb-crested Jacana</td>
<td>81</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>https://biodiversity.org.au/afd/taxa/8bf4b8b0-...</td>
<td>Daphoenositta (Neositta) chrysoptera</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Neosittidae</td>
<td>Daphoenositta</td>
<td>Varied Sittella</td>
<td>59</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>https://biodiversity.org.au/afd/taxa/fe74e658-...</td>
<td>Petroica (Littlera) phoenicea</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Petroicidae</td>
<td>Petroica</td>
<td>Flame Robin</td>
<td>45</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>https://biodiversity.org.au/afd/taxa/cc5315bf-...</td>
<td>Pseudophryne pengilleyi</td>
<td>Wells &amp; Wellington, 1985</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Myobatrachidae</td>
<td>Pseudophryne</td>
<td>Northern Corroboree Frog</td>
<td>33</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>https://biodiversity.org.au/afd/taxa/2063bf6d-...</td>
<td>Pachycephala (Timixos) olivacea</td>
<td>Vigors &amp; Horsfield, 1827</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Pachycephalidae</td>
<td>Pachycephala</td>
<td>Olive Whistler</td>
<td>28</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>https://biodiversity.org.au/afd/taxa/6e872b58-...</td>
<td>Stagonopleura (Stagonopleura) guttata</td>
<td>(Shaw, 1796)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Estrildidae</td>
<td>Stagonopleura</td>
<td>Diamond Firetail</td>
<td>28</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>https://biodiversity.org.au/afd/taxa/b47a4ecd-...</td>
<td>Hieraaetus (Hieraaetus) morphnoides</td>
<td>(Gould, 1841)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Hieraaetus</td>
<td>Little Eagle</td>
<td>23</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>https://biodiversity.org.au/afd/taxa/cd4e3b1b-...</td>
<td>Burhinus (Burhinus) grallarius</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Charadriiformes</td>
<td>Burhinidae</td>
<td>Burhinus</td>
<td>Bush Stone-curlew</td>
<td>13</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>https://biodiversity.org.au/afd/taxa/19c9bfdf-...</td>
<td>Bettongia gaimardi</td>
<td>(Desmarest, 1822)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Potoroidae</td>
<td>Bettongia</td>
<td>Tasmanian Bettong</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">12</td>
<td>https://biodiversity.org.au/afd/taxa/d1c5dee0-...</td>
<td>Ninox (Rhabdoglaux) strenua</td>
<td>(Gould, 1838)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Strigiformes</td>
<td>Strigidae</td>
<td>Ninox</td>
<td>Powerful Owl</td>
<td>6</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">13</td>
<td>https://biodiversity.org.au/afd/taxa/dc420306-...</td>
<td>Haliaeetus (Pontoaetus) leucogaster</td>
<td>(Gmelin, 1788)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Haliaeetus</td>
<td>White-bellied Sea-eagle</td>
<td>6</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">14</td>
<td>https://biodiversity.org.au/afd/taxa/52149285-...</td>
<td>Dasyurus viverrinus</td>
<td>(Shaw, 1800)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Dasyuromorphia</td>
<td>Dasyuridae</td>
<td>Dasyurus</td>
<td>Eastern Quoll</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">15</td>
<td>https://biodiversity.org.au/afd/taxa/a51dca29-...</td>
<td>Synemon plana</td>
<td>Walker, 1854</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Lepidoptera</td>
<td>Castniidae</td>
<td>Synemon</td>
<td>Golden Sun Moth</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">16</td>
<td>https://biodiversity.org.au/afd/taxa/c95af018-...</td>
<td>Epthianura (Epthianura) albifrons</td>
<td>(Jardine &amp; Selby, 1828)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Meliphagidae</td>
<td>Epthianura</td>
<td>White-fronted Chat</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">17</td>
<td>https://id.biodiversity.org.au/node/apni/2910323</td>
<td>Ammobium craspedioides</td>
<td>Benth.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Ammobium</td>
<td>Yass Daisy</td>
<td>5</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">18</td>
<td>https://id.biodiversity.org.au/node/apni/2918079</td>
<td>Wilsonia rotundifolia</td>
<td>Hook.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Solanales</td>
<td>Convolvulaceae</td>
<td>Wilsonia</td>
<td>Roundleaf Wilsonia</td>
<td>5</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">19</td>
<td>https://biodiversity.org.au/afd/taxa/694a8fde-...</td>
<td>Circus assimilis</td>
<td>Jardine &amp; Selby, 1828</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Accipitriformes</td>
<td>Accipitridae</td>
<td>Circus</td>
<td>Spotted Harrier</td>
<td>4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">20</td>
<td>https://biodiversity.org.au/afd/taxa/32f9229c-...</td>
<td>Oxyura australis</td>
<td>Gould, 1837</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Anseriformes</td>
<td>Anatidae</td>
<td>Oxyura</td>
<td>Blue-billed Duck</td>
<td>3</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">21</td>
<td>https://id.biodiversity.org.au/taxon/apni/5128...</td>
<td>Leucochrysum albicans</td>
<td>(A.Cunn.) Paul G.Wilson</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Leucochrysum</td>
<td>NaN</td>
<td>3</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22</td>
<td>https://biodiversity.org.au/afd/taxa/dba78701-...</td>
<td>Botaurus poiciloptilus</td>
<td>(Wagler, 1827)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Ciconiiformes</td>
<td>Ardeidae</td>
<td>Botaurus</td>
<td>Australasian Bittern</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">23</td>
<td>https://id.biodiversity.org.au/node/apni/2920809</td>
<td>Eucalyptus pumila</td>
<td>Cambage</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Pokolbin Mallee</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">24</td>
<td>https://id.biodiversity.org.au/node/apni/7062437</td>
<td>Rutidosis leptorhynchoides</td>
<td>F.Muell.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Asterales</td>
<td>Asteraceae</td>
<td>Rutidosis</td>
<td>Button Wrinklewort</td>
<td>2</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">25</td>
<td>https://id.biodiversity.org.au/taxon/apni/5129...</td>
<td>Eucalyptus radiata</td>
<td>Sieber ex DC.</td>
<td>species</td>
<td>Plantae</td>
<td>Charophyta</td>
<td>Equisetopsida</td>
<td>Myrtales</td>
<td>Myrtaceae</td>
<td>Eucalyptus</td>
<td>Narrow-leaved Peppermint</td>
<td>2</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">26</td>
<td>https://biodiversity.org.au/afd/taxa/0aa4d63d-...</td>
<td>Keyacris scurra</td>
<td>(Rehn, 1952)</td>
<td>species</td>
<td>Animalia</td>
<td>Arthropoda</td>
<td>Insecta</td>
<td>Orthoptera</td>
<td>Morabidae</td>
<td>Keyacris</td>
<td>Key's Matchstick Grasshopper</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">27</td>
<td>https://biodiversity.org.au/afd/taxa/1b653e0c-...</td>
<td>Petaurus norfolcensis</td>
<td>(Kerr, 1792)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Petauridae</td>
<td>Petaurus</td>
<td>Squirrel Glider</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">28</td>
<td>https://biodiversity.org.au/afd/taxa/320aeab1-...</td>
<td>Artamus (Angroyan) cyanopterus</td>
<td>(Latham, 1801)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Aves</td>
<td>Passeriformes</td>
<td>Artamidae</td>
<td>Artamus</td>
<td>Dusky Woodswallow</td>
<td>1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">29</td>
<td>https://biodiversity.org.au/afd/taxa/5557cf29-...</td>
<td>Litoria verreauxii</td>
<td>(DumÃ©ril, 1853)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Amphibia</td>
<td>Anura</td>
<td>Hylidae</td>
<td>Litoria</td>
<td>Verreaux's Frog</td>
<td>1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">30</td>
<td>https://biodiversity.org.au/afd/taxa/e9d6fbbd-...</td>
<td>Phascolarctos cinereus</td>
<td>(Goldfuss, 1817)</td>
<td>species</td>
<td>Animalia</td>
<td>Chordata</td>
<td>Mammalia</td>
<td>Diprotodontia</td>
<td>Phascolarctidae</td>
<td>Phascolarctos</td>
<td>Koala</td>
<td>1</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Now, if you want to save this data to a file, you can use the <code>to_csv</code> function in <code>pandas</code>.</p>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species <span class="op">=</span> galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>])</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species_counts <span class="op">=</span> galah.atlas_species(polygon<span class="op">=</span>yass_valley_geometry_degrees_buffer[<span class="dv">127</span>],filters<span class="op">=</span>[<span class="st">"year=2023"</span>,<span class="st">"species_list_uid=dr650"</span>],counts<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species.to_csv(<span class="st">"yass_valley_species_buffer_sensitive_species.csv"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>yass_valley_species_buffer_sensitive_species_counts.to_csv(<span class="st">"yass_valley_species_buffer_sensitive_species_counts.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>